import { Component, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort, MatSortable } from '@angular/material/sort';

@Component({
  selector: 'app-pesquisa',
  templateUrl: './pesquisa.component.html',
  styleUrls: ['./pesquisa.component.scss'],
})
export class PesquisaComponent {
  displayedColumns: string[] = ['sobrenome', 'nome'];
  dataSource = new MatTableDataSource<Familias>(ELEMENT_DATA);

  @ViewChild(MatPaginator) paginator!: MatPaginator;
  @ViewChild(MatSort) sort!: MatSort;

  ngAfterViewInit() {
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;

    this.sort.sort({ id: 'sobrenome', start: 'asc' } as MatSortable);
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();

    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }
}

export interface Familias {
  nome: string;
  sobrenome: string;
}

const ELEMENT_DATA: Familias[] = [
  { sobrenome: 'Baptistelli', nome: ' Adamo' },
  { sobrenome: 'Ferraresi', nome: 'Adelaide' },
  { sobrenome: 'Cani', nome: 'Adolfo' },
  { sobrenome: 'Casini', nome: 'Adolfo' },
  { sobrenome: 'Marchesini', nome: 'Adolpho' },
  { sobrenome: 'Auricchio', nome: 'Agnello' },
  { sobrenome: 'Mulotto', nome: 'Agnese' },
  { sobrenome: 'Petrucci', nome: 'Alberto' },
  { sobrenome: 'Guizzardo', nome: 'Alessandro' },
  { sobrenome: 'Freddi', nome: 'Amabile' },
  { sobrenome: 'Ghizzi', nome: 'Amedeo' },
  { sobrenome: 'Pagnoncelli', nome: 'Andrea' },
  { sobrenome: 'Bandoria', nome: 'Angela' },
  { sobrenome: 'Agarella', nome: 'Angelo' },
  { sobrenome: 'Cantiero', nome: 'Angelo' },
  { sobrenome: 'Falcone', nome: 'Angelo' },
  { sobrenome: 'Lazarotto', nome: 'Angelo' },
  { sobrenome: 'Natali', nome: 'Angelo' },
  { sobrenome: 'Pavan', nome: 'Angelo' },
  { sobrenome: 'Pietrobon', nome: 'Angelo' },
  { sobrenome: 'Piovan', nome: 'Angelo' },
  { sobrenome: 'Lenoci', nome: 'Angiola' },
  { sobrenome: 'Della Bin', nome: 'Annunziata' },
  { sobrenome: 'Piangerelli', nome: 'Annunziata' },
  { sobrenome: 'Reginatto', nome: 'Antonia' },
  { sobrenome: 'Vasta', nome: 'Antonina' },
  { sobrenome: 'Ardigò', nome: 'Antonio' },
  { sobrenome: 'Balzano', nome: 'Antonio' },
  { sobrenome: 'Borotto', nome: 'Antonio' },
  { sobrenome: 'Cantalupo', nome: 'Antonio' },
  { sobrenome: 'Carnevali', nome: 'Antonio' },
  { sobrenome: 'Cechelero', nome: 'Antonio' },
  { sobrenome: 'Faggion', nome: 'Antonio' },
  { sobrenome: 'Giannini', nome: 'Antonio' },
  { sobrenome: 'Marcuzzo', nome: 'Antonio' },
  { sobrenome: 'Martinello', nome: 'Antonio' },
  { sobrenome: 'Passarin', nome: 'Antonio' },
  { sobrenome: 'Verdi', nome: 'Antonio' },
  { sobrenome: 'Zalamena', nome: 'Arcangelo' },
  { sobrenome: 'Luppi', nome: 'Aristea' },
  { sobrenome: 'Buzzini', nome: 'Arthur' },
  { sobrenome: 'Scattolini', nome: 'Attilio' },
  { sobrenome: 'Agnolini', nome: 'Augusto' },
  { sobrenome: 'Stimmatini', nome: 'Augusto' },
  { sobrenome: 'Zardini', nome: 'Augusto' },
  { sobrenome: 'Baldocchi', nome: 'Balilla' },
  { sobrenome: 'Baccin', nome: 'Benedetto' },
  { sobrenome: 'Costantino', nome: 'Benedetto' },
  { sobrenome: 'Bachini', nome: 'Benedicto' },
  { sobrenome: 'Sebastiano', nome: 'Bortolo' },
  { sobrenome: 'Decorato', nome: 'Carlo' },
  { sobrenome: 'Sirtori', nome: 'Carlo' },
  { sobrenome: 'Martillotta', nome: 'Carmela' },
  { sobrenome: 'Maimone', nome: 'Carmine' },
  { sobrenome: 'Visentin', nome: 'Catherina' },
  { sobrenome: 'Lorenzini', nome: 'Cecilia' },
  { sobrenome: 'Nico', nome: 'Cesare' },
  { sobrenome: 'Rizzi', nome: 'Dirthea' },
  { sobrenome: 'Montagner', nome: 'Domenica' },
  { sobrenome: 'Arselli', nome: 'Domenico' },
  { sobrenome: 'Bernardine', nome: 'Domenico' },
  { sobrenome: 'Da Ros', nome: 'Domenico' },
  { sobrenome: 'Gioia', nome: 'Domenico' },
  { sobrenome: 'Luciani', nome: 'Domenico' },
  { sobrenome: 'Presotto', nome: 'Domenico' },
  { sobrenome: 'Pretto', nome: 'Domenico' },
  { sobrenome: 'Scaffini', nome: 'Domenico' },
  { sobrenome: 'Schiaffini', nome: 'Domenico' },
  { sobrenome: 'Tonet', nome: 'Domenico' },
  { sobrenome: 'Tonetti', nome: 'Domenico' },
  { sobrenome: 'Pisi', nome: 'Elvira' },
  { sobrenome: 'Bella', nome: 'Emilia' },
  { sobrenome: 'Bello', nome: 'Emilia' },
  { sobrenome: 'Lucchini', nome: 'Emilio' },
  { sobrenome: 'Campi', nome: 'Enrico' },
  { sobrenome: 'Gallo', nome: 'Enrico' },
  { sobrenome: 'Righetto', nome: 'Ermenegildo' },
  { sobrenome: 'Pessetta', nome: 'Erminia' },
  { sobrenome: 'Dal Bello', nome: 'Eugenio' },
  { sobrenome: 'Bissoli', nome: 'Eva' },
  { sobrenome: 'Giacometti', nome: 'Felice' },
  { sobrenome: 'Jacometti', nome: 'Felice' },
  { sobrenome: 'Di Spirito', nome: 'Filippo' },
  { sobrenome: 'Spirito', nome: 'Filippo' },
  { sobrenome: 'Cenci', nome: 'Francesco' },
  { sobrenome: 'Graziani', nome: 'Francesco' },
  { sobrenome: 'Jannotti', nome: 'Francesco' },
  { sobrenome: 'Pagliocchi', nome: 'Francesco' },
  { sobrenome: 'Parise', nome: 'Francesco' },
  { sobrenome: 'Vaccaro', nome: 'Francesco' },
  { sobrenome: 'Ferrari', nome: 'Gaetano' },
  { sobrenome: 'Esposito', nome: 'Gennaro' },
  { sobrenome: 'Tartarelli', nome: 'Geraldo' },
  { sobrenome: 'Cascardo', nome: 'Giacomo' },
  { sobrenome: 'Colosio', nome: 'Giacomo' },
  { sobrenome: 'Pastres', nome: 'Giacomo' },
  { sobrenome: 'Pellizzaro', nome: 'Giacomo' },
  { sobrenome: 'Covolo', nome: 'GioBatta' },
  { sobrenome: 'Crivellari', nome: 'GioBatta' },
  { sobrenome: 'Barbon', nome: 'Giovanni' },
  { sobrenome: 'Basso', nome: 'Giovanni' },
  { sobrenome: 'Bergamasco', nome: 'Giovanni' },
  { sobrenome: 'Bottecchia', nome: 'Giovanni' },
  { sobrenome: 'Cristoffolo', nome: 'Giovanni' },
  { sobrenome: 'Dattrino', nome: 'Giovanni' },
  { sobrenome: 'Eredi', nome: 'Giovanni' },
  { sobrenome: 'Ferro', nome: 'Giovanni' },
  { sobrenome: 'Giulino', nome: 'Giovanni' },
  { sobrenome: 'Magri', nome: 'Giovanni' },
  { sobrenome: 'Nicotra', nome: 'Giovanni' },
  { sobrenome: 'Pessini', nome: 'Giovanni' },
  { sobrenome: 'Pizzi', nome: 'Giovanni' },
  { sobrenome: 'Rogna', nome: 'Giovanni' },
  { sobrenome: 'Stella', nome: 'Giovanni' },
  { sobrenome: 'Bargieri', nome: 'Giuseppe' },
  { sobrenome: 'Bianchini', nome: 'Giuseppe' },
  { sobrenome: 'Bianucci', nome: 'Giuseppe' },
  { sobrenome: 'Busnardo', nome: 'Giuseppe' },
  { sobrenome: 'Chiodi', nome: 'Giuseppe' },
  { sobrenome: 'Garusi', nome: 'Giuseppe' },
  { sobrenome: 'Guerra', nome: 'Giuseppe' },
  { sobrenome: 'Limoli', nome: 'Giuseppe' },
  { sobrenome: 'Lippi', nome: 'Giuseppe' },
  { sobrenome: 'Ludovico', nome: 'Giuseppe' },
  { sobrenome: 'Lupino', nome: 'Giuseppe' },
  { sobrenome: 'Mariani', nome: 'Giuseppe' },
  { sobrenome: 'Marin', nome: 'Giuseppe' },
  { sobrenome: 'Schiavinato', nome: 'Giuseppe' },
  { sobrenome: 'Tavolazzi', nome: 'Giuseppe' },
  { sobrenome: 'Zarella', nome: 'Giuseppe' },
  { sobrenome: 'Segala', nome: 'Giuseppina' },
  { sobrenome: 'Da Roit', nome: 'Guerino' },
  { sobrenome: 'Zanon', nome: 'Guerino' },
  { sobrenome: 'Maistrelli', nome: 'Guido' },
  { sobrenome: 'Maistrello', nome: 'Guido' },
  { sobrenome: 'Rossi', nome: 'Iginio' },
  { sobrenome: 'Gazella', nome: 'Jacintha' },
  { sobrenome: 'Latrofa', nome: 'José' },
  { sobrenome: 'Celeghin', nome: 'Julio' },
  { sobrenome: 'Vasconi', nome: 'Lucia' },
  { sobrenome: 'Ambrosio', nome: 'Luigi' },
  { sobrenome: 'Andreatta', nome: 'Luigi' },
  { sobrenome: 'Benassi', nome: 'Luigi' },
  { sobrenome: 'Bonometti', nome: 'Luigi' },
  { sobrenome: 'Bruno', nome: 'Luigi' },
  { sobrenome: 'De Vulcanis', nome: 'Luigi' },
  { sobrenome: 'Ferrara', nome: 'Luigi' },
  { sobrenome: 'Ferraro', nome: 'Luigi' },
  { sobrenome: 'Gregolon', nome: 'Luigi' },
  { sobrenome: 'Mantegazzini', nome: 'Luigi' },
  { sobrenome: 'Marchiori', nome: 'Luigi' },
  { sobrenome: 'Sorati', nome: 'Luigi' },
  { sobrenome: 'Stoppa', nome: 'Luigi' },
  { sobrenome: 'Vicari', nome: 'Luigi' },
  { sobrenome: 'Angeli', nome: 'Luigia' },
  { sobrenome: 'Schiavon', nome: 'Luigia' },
  { sobrenome: 'Tassotti', nome: 'Luigia' },
  { sobrenome: 'Camminada', nome: 'Maddalena' },
  { sobrenome: 'Modesto', nome: 'Manoel' },
  { sobrenome: 'Rossetti', nome: 'Marcelo' },
  { sobrenome: 'Bovo', nome: 'Marcos' },
  { sobrenome: 'Barbiani', nome: 'Maria' },
  { sobrenome: 'Barbieri', nome: 'Maria' },
  { sobrenome: 'Cagliari', nome: 'Maria' },
  { sobrenome: 'Cavalli', nome: 'Maria' },
  { sobrenome: 'Dell Ova', nome: 'Maria' },
  { sobrenome: 'Moreni', nome: 'Maria' },
  { sobrenome: 'Pividori', nome: 'Maria' },
  { sobrenome: 'Vignati', nome: 'Maria' },
  { sobrenome: 'Villani', nome: 'Maria' },
  { sobrenome: 'Losi', nome: 'Marinho' },
  { sobrenome: 'Tonetto', nome: 'Mose' },
  { sobrenome: 'Manganelli', nome: 'Nazzareno' },
  { sobrenome: 'Cappelletti', nome: 'Nicola' },
  { sobrenome: 'Massimo', nome: 'Nicola' },
  { sobrenome: 'Fantini', nome: 'Nicolau' },
  { sobrenome: 'Vertova', nome: 'Odetta' },
  { sobrenome: 'Bortolusso', nome: 'Olimpia' },
  { sobrenome: 'Barrai', nome: 'Paolo' },
  { sobrenome: 'Grassi', nome: 'Paolo' },
  { sobrenome: 'Pellizon', nome: 'Pasquale' },
  { sobrenome: 'Scita', nome: 'Pasquale' },
  { sobrenome: 'Veneziano', nome: 'Pasqualina' },
  { sobrenome: 'Bellini', nome: 'Pietro' },
  { sobrenome: 'Favarin', nome: 'Pietro' },
  { sobrenome: 'Peluzzo', nome: 'Pietro' },
  { sobrenome: 'Santilone', nome: 'Pietro' },
  { sobrenome: 'Simon', nome: 'Pietro' },
  { sobrenome: 'Zanella', nome: 'Pietro' },
  { sobrenome: 'Brambillasca', nome: 'Rachelle' },
  { sobrenome: 'Turani', nome: 'Raffael' },
  { sobrenome: 'Milanesi', nome: 'Regina' },
  { sobrenome: 'Braccini', nome: 'Reynaldo' },
  { sobrenome: 'Bocchi', nome: 'Ricardo' },
  { sobrenome: 'Bellinfante', nome: 'Rosa' },
  { sobrenome: 'Citante', nome: 'Rosa' },
  { sobrenome: 'Denti', nome: 'Rosa' },
  { sobrenome: 'Maggion', nome: 'Rosa' },
  { sobrenome: 'Marchesin', nome: 'Rosa' },
  { sobrenome: 'Russo', nome: 'Rosa' },
  { sobrenome: 'Rondi', nome: 'Rosalina' },
  { sobrenome: 'Pantoni', nome: 'Sabatino' },
  { sobrenome: 'De Domenico', nome: 'Salvatore' },
  { sobrenome: 'Crepaldi', nome: 'Santa' },
  { sobrenome: 'Timpanaro', nome: 'Santa' },
  { sobrenome: 'Ferretti', nome: 'Scilide' },
  { sobrenome: 'Bortolo', nome: 'Sebastiano' },
  { sobrenome: 'Galli', nome: 'Setimina' },
  { sobrenome: 'Amato', nome: 'Silvestre' },
  { sobrenome: 'Amata', nome: 'Silvestro' },
  { sobrenome: 'Bissaro', nome: 'Silvio' },
  { sobrenome: 'Bergamaschi', nome: 'Teresa' },
  { sobrenome: 'Guidolin', nome: 'Teresa' },
  { sobrenome: 'Biagioni', nome: 'Ubaldo' },
  { sobrenome: 'Melloni', nome: 'Ugo' },
  { sobrenome: 'Magi', nome: 'Umberto' },
  { sobrenome: 'Bissolotti', nome: 'Veneranda' },
  { sobrenome: 'Morini', nome: 'Veronica' },
  { sobrenome: 'Grecco', nome: 'Vicenzo' },
  { sobrenome: 'Palombo', nome: 'Vincenzo' },
  { sobrenome: 'Durigon', nome: 'Virginia' },
  { sobrenome: 'Abramo', nome: 'Vito' },
  { sobrenome: 'Ragazini', nome: 'Vito' },
  { sobrenome: 'Calzavara', nome: 'Vittorio' },
  { sobrenome: 'Montresor', nome: 'Vittorio' },
  { sobrenome: 'Jacopucci', nome: 'Biagio' },
  { sobrenome: 'Schionato', nome: 'Marianna' },
  { sobrenome: 'Bresciani', nome: 'Margherita' },
  { sobrenome: 'Michelucci', nome: 'Alfredo' },
  { sobrenome: 'Turcinelli', nome: 'Gennaro' },
  { sobrenome: 'Tadei', nome: 'Antonia' },
  { sobrenome: 'Vezzu', nome: 'Antonietta' },
  { sobrenome: 'Palei', nome: 'Luigi' },
  { sobrenome: 'Macaro', nome: 'Rosaria' },
  { sobrenome: 'Venturini', nome: 'Giacinto' },
  { sobrenome: 'Scariot', nome: 'Costante' },
  { sobrenome: 'Scandolara', nome: 'Luigia' },
  { sobrenome: 'Dendena', nome: 'Michele' },
  { sobrenome: 'Boschesi', nome: 'Guido' },
  { sobrenome: 'Pircio', nome: 'Domenico' },
  { sobrenome: 'Roncari', nome: 'Margherita' },
  { sobrenome: 'Festa', nome: 'Virginio' },
  { sobrenome: 'Florio', nome: 'Anna' },
  { sobrenome: 'Siga', nome: 'Affonso' },
  { sobrenome: 'Beloti', nome: 'Battista' },
  { sobrenome: 'Filice', nome: 'Amedeo' },
  { sobrenome: 'Caserta', nome: 'Giuseppe' },
  { sobrenome: 'Romano', nome: 'Maria' },
  { sobrenome: 'Carnicelli', nome: 'Maria' },
  { sobrenome: 'Origgi', nome: 'Giuseppe' },
  { sobrenome: 'Cerchi', nome: 'Giuseppina' },
  { sobrenome: 'Sebastiani', nome: 'Pietro' },
  { sobrenome: 'Toffetti', nome: 'Christofforo' },
  { sobrenome: 'Santin', nome: 'Vincenzo' },
  { sobrenome: 'Bonatti', nome: 'Maurizio' },
  { sobrenome: 'Baraldi', nome: 'Silvia' },
  { sobrenome: 'Cammarota', nome: 'Luciano' },
  { sobrenome: 'Spinelli', nome: 'Maria' },
  { sobrenome: 'Rajola', nome: 'Ciro' },
  { sobrenome: 'D Amico', nome: 'Fiorina' },
  { sobrenome: 'Regal', nome: 'Vicenzo' },
  { sobrenome: 'Lecci', nome: 'Anna' },
  { sobrenome: 'Coletto', nome: 'Gioachino' },
  { sobrenome: 'Reale', nome: 'Vicenzo' },
  { sobrenome: 'Calegari', nome: 'Thereza' },
  { sobrenome: 'Reati', nome: 'Adele' },
  { sobrenome: 'Galera', nome: 'Francesco' },
  { sobrenome: 'Corazza', nome: 'Antonia' },
  { sobrenome: 'Zambolli', nome: 'Albino' },
  { sobrenome: 'Massarente', nome: 'Virginia' },
  { sobrenome: 'Boldrini', nome: 'Giovanni' },
  { sobrenome: 'Casali', nome: 'Luigi' },
  { sobrenome: 'De Carli', nome: 'Carlo' },
  { sobrenome: 'Muratore', nome: 'Giovanni' },
  { sobrenome: 'Provedella', nome: 'Regina' },
  { sobrenome: 'Berlato', nome: 'Federico' },
  { sobrenome: 'Minichillo', nome: 'Pietro' },
  { sobrenome: 'Sambogna', nome: 'Giovanna' },
  { sobrenome: 'De Rossi', nome: 'Antonio' },
  { sobrenome: 'Biancchini', nome: 'Giuseppe' },
  { sobrenome: 'Moretto', nome: 'Amalia' },
  { sobrenome: 'Morinelli', nome: 'Angiola' },
  { sobrenome: 'Gatti', nome: 'Anna' },
  { sobrenome: 'Montin', nome: 'Paolo' },
  { sobrenome: 'Occhial', nome: 'Elisabetta' },
  { sobrenome: 'Motta', nome: 'Benedetto' },
  { sobrenome: 'Campagnolo', nome: 'Angiola' },
  { sobrenome: 'Mantovani', nome: 'Luigi' },
  { sobrenome: 'Burim', nome: 'Maria' },
  { sobrenome: 'Vittorazzo', nome: 'Oliva' },
  { sobrenome: 'Bertuolo', nome: 'Marco' },
  { sobrenome: 'Tellaroli', nome: 'Bortolo' },
  { sobrenome: 'Benazzati', nome: 'Giuseppe' },
  { sobrenome: 'Ballestrero', nome: 'Giuseppe' },
  { sobrenome: 'Rachini', nome: 'Maria' },
  { sobrenome: 'Pierri', nome: 'Francesco' },
  { sobrenome: 'Lucente', nome: 'Lunetta' },
  { sobrenome: 'Lallo', nome: 'Giuseppe' },
  { sobrenome: 'Rizzo', nome: 'Vicenzo' },
  { sobrenome: 'Balbi', nome: 'Vicentina' },
  { sobrenome: 'Carreri', nome: 'Giuseppe' },
  { sobrenome: 'Galazzi', nome: 'Giudita' },
  { sobrenome: 'Cetrangolo', nome: 'Gennaro' },
  { sobrenome: 'Spugnardi', nome: 'Filomena' },
  { sobrenome: 'Capodano', nome: 'Dolores' },
  { sobrenome: 'Terazzi', nome: 'Natale' },
  { sobrenome: 'Signorinni', nome: 'Maria' },
  { sobrenome: 'Aguida', nome: 'Adelaide' },
  { sobrenome: 'Martinelli', nome: 'Ercole' },
  { sobrenome: 'Bariviera', nome: 'Giovanni' },
  { sobrenome: 'Cilotto', nome: 'Gracia' },
  { sobrenome: 'Biglia', nome: 'Luigi' },
  { sobrenome: 'Sannino', nome: 'Michele' },
  { sobrenome: 'Graciolli', nome: 'Giuseppe' },
  { sobrenome: 'Marcante', nome: 'Maria' },
  { sobrenome: 'Corrao', nome: 'Francesco' },
  { sobrenome: 'Onorato', nome: 'Gracia' },
  { sobrenome: 'Scarfon', nome: 'Domenico' },
  { sobrenome: 'Bianchi', nome: 'Maria' },
  { sobrenome: 'Bisio', nome: 'Lorenzo' },
  { sobrenome: 'Bottaro', nome: 'Maria' },
  { sobrenome: 'Paciullo', nome: 'Domenico' },
  { sobrenome: 'Brunetti', nome: 'Maria' },
  { sobrenome: 'Pattoli', nome: 'Giovanni' },
  { sobrenome: 'Gioachino', nome: 'Vicenzo' },
  { sobrenome: 'Pastorello', nome: 'Eugenio' },
  { sobrenome: 'Braghin', nome: 'Rosa' },
  { sobrenome: 'Soave', nome: 'Maria' },
  { sobrenome: 'Tartaglione', nome: 'Marianna' },
  { sobrenome: 'Mormile', nome: 'Vicenzo' },
  { sobrenome: 'Gasparini', nome: 'Pietro' },
  { sobrenome: 'Grespi', nome: 'Isabella' },
  { sobrenome: 'Cavicchioli', nome: 'Luigi' },
  { sobrenome: 'Portieri', nome: 'Henriqueta' },
  { sobrenome: 'Zunino', nome: 'Maria' },
  { sobrenome: 'Donadel', nome: 'Giuseppe' },
  { sobrenome: 'Ragusi', nome: 'Elena' },
  { sobrenome: 'Lusa', nome: 'Giovanni' },
  { sobrenome: 'Iuliano', nome: 'Costanza' },
  { sobrenome: 'Ridolfi', nome: 'Vincenzo' },
  { sobrenome: 'Mazza', nome: 'Antonio' },
  { sobrenome: 'Gris', nome: 'Maria' },
  { sobrenome: 'Grotti', nome: 'Thereza' },
  { sobrenome: 'Nicoletti', nome: 'Jacob' },
  { sobrenome: 'Bogo', nome: 'Antonio' },
  { sobrenome: 'Bianco', nome: 'Maria' },
  { sobrenome: 'Zuccolo', nome: 'Luigi' },
  { sobrenome: 'De Luca', nome: 'Felice' },
  { sobrenome: 'Bonamigo', nome: 'Giovanni' },
  { sobrenome: 'Cavini', nome: 'Antonio' },
  { sobrenome: 'De Nadai', nome: 'Natale' },
  { sobrenome: 'Moret', nome: 'Maria' },
  { sobrenome: 'Chiggio', nome: 'Giovanni' },
  { sobrenome: 'Donà', nome: 'Antonio' },
  { sobrenome: 'Corsini', nome: 'Luigi' },
];
